<?php echo $this->form()->openTag($form)?>
<?php echo $this->formelement($form->get('produto_id'))?>
<table class="table">
    <tr>
        <td><?php echo $this->formlabel($form->get('produto_nome'))?></td>
        <td>
            <?php echo $this->formelement($form->get('produto_nome'))?>
            <?php echo $this->formelementerrors($form->get('produto_nome'))?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('produto_preco'))?></td>
        <td>
            <?php echo $this->formelement($form->get('produto_preco'))?>
            <?php echo $this->formelementerrors($form->get('produto_preco'))?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('produto_foto'))?></td>
        <td>
            <?php echo $this->formelement($form->get('produto_foto'))?>
            <?php echo $this->formelementerrors($form->get('produto_foto'))?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('produto_descricao'))?></td>
        <td>
            <?php echo $this->formelement($form->get('produto_descricao'))?>
            <?php echo $this->formelementerrors($form->get('produto_descricao'))?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('produto_status'))?></td>
        <td>
            <?php echo $this->formelement($form->get('produto_status'))?>
            <?php echo $this->formelementerrors($form->get('produto_status'))?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->formlabel($form->get('submit'))?></td>
        <td>
        <?php echo $this->formelement($form->get('submit'))?>
        <a class="btn" href="index">Cancelar</a>
        </td>
    </tr>
</table>

<?php echo $this->form()->closeTag($form)?>